### ISSUE TITLE
Notifications not working 

### ISSUE THREAD

**Issue by thiswastheonlyavailableusername** [xManager-App/xManager#187]
I don't get notified of new Spotify or manager versions.

 - Device: Nokia 3.4
 - OS: Android 11
 - Version 4.0

I don't see a setting to turn notifications on. Is it supposed to work like this?

**Comment by energ0n** [comment]
App notifications are handled outside of the in-app settings/options menu and instead are controlled by android via the `App info` submenu for xManager (where you can set app permissions, clear cache/data, etc). Confirm you have notifications enabled there.

**Comment by thiswastheonlyavailableusername** [comment]
I confirm notifications are enabled.
And even though I installed the app on a new device, I still have the same issue.

App version: 4.3
Device: Motorola G32
Android 11

**Comment by energ0n** [comment]
> I confirm notifications are enabled. And even though I installed the app on a new device, I still have the same issue.
> 
> App version: 4.3 Device: Motorola G32 Android 11

Sorry for the delayed reply. 

Due to switching database hosts, xManager no longer has push notifications when new versions are released. 
Checking the app every now and then or keeping up with announcements on our social media outlets are the best way to see updates. 

•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
