### ISSUE TITLE
Virus detected in VT

### ISSUE THREAD

**Issue by Skyhawk1207** [xManager-App/xManager#322]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  One Plus 8
- Android Version:  Android 12
- ROM Version:  ColorOS
- xManager Version:  Latest
```

### 📝 Description

This app is showing as a virus in VirusTotal under 2 sources, one of them being Google. Can we get that remediated, as it might cause trust issues?

### 📸 Screenshots

![23-19-23-122320](https://github.com/xManager-App/xManager/assets/68462875/db5d2710-a6f4-4f79-88b8-f5ef59ef3db2)

**Comment by xC3FFF0E** [comment]
False positives. That "trojan" flagged is most likely because the apk is obfucated and we're using a modified proguard (check hybrid analysis). The "google" flagged is for the advertisement and most of its resources. We already reported this to virus-total and yet they keep flagging this version.

TL:DR: The file is marked as clean and was only labeled as generic trojan (false positive).

Official VT: https://www.virustotal.com/gui/file/bd772703dd901df2eb01720efebde78e6b73c8974f6f2d36ca12af95ae73c281/detection

**Comment by xC3FFF0E** [comment]
**UPDATE:** 4.9 has been reuploaded without any obfuscation.

**VT Link:** https://www.virustotal.com/gui/file/994ea1d7b7cea1ab7f9ffb18b24ea8f58cd9d511ac8c5dc967d47207c55fa891/detection

**Comment by Skyhawk1207** [comment]
My concern is resolved. Thank you!!
